FROM leifg/elixir:latest

MAINTAINER Yeong Sheng, Tan <tanyeongsheng@gmail.com>
# Tooling from hex mix_docker expects app install to be in /opt/app
ENV REFRESHED_AT=2017-Mar-29 \
    LANG=en_US.UTF-8 \
    HOME=/opt/app/ \
    TERM=xterm

# Install Elixir and basic build dependencies
# Base Erlang packages required:
# erlang-kernel (19.1.0-r0)
# erlang-stdlib (19.1.0-r0)
# erlang-compiler (19.1.0-r0)
# erlang (19.1.0-r0)
# erlang-inets (19.1.0-r0)
# erlang-ssl (19.1.0-r0)
# erlang-public-key (19.1.0-r0)
# erlang-asn1 (19.1.0-r0)
# erlang-sasl (19.1.0-r0)
# erlang-erl-interface (19.1.0-r0)
# erlang-dev (19.1.0-r0)

RUN \
    echo "@edge http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache --update add git make g++ protobuf@edge && \
    rm -rf /var/cache/apk/*

# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez && \
    mix hex.info

WORKDIR /opt/app

ENV MIX_ENV=prod

# Cache elixir deps
COPY . . 
RUN mix do deps.update --all, deps.compile, phx.digest, release --env=prod --verbose