version: "3"
services:
  icx_manager:
    image: elixirsg_alp/rna_umbrella:release
    command: /opt/app/bin/rna_umbrella foreground
    environment:
      - MIX_ENV=prod
      - PORT=9000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    hostname: icx
    domainname: icx.com
    # network_mode: "host"
    ports:
      - "8000:9000"
    depends_on:
      - postgres
      - mosquitto_broker1
      - mosquitto_broker2

  postgres:
    image: postgres:10.1
    ports:
      - "5432"

  mosquitto_broker1:
    image: erlio/docker-vernemq
    ports:
      - "3883:1883"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on

  mosquitto_broker2:
    image: erlio/docker-vernemq 
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on 
      - DOCKER_VERNEMQ_DISCOVERY_NODE=mosquitto_broker1
    depends_on:
      - mosquitto_broker1
