FROM bitwalker/alpine-elixir:1.6.1

MAINTAINER Yeong Sheng, Tan <tanyeongsheng@gmail.com>
ENV REFRESHED_AT=2018-Jan-31 \
    SHELL=/bin/sh \
    LANG=en_US.UTF-8 \
    LC_ALL=${LANG} \
    HOME=/opt/app/ \
    TERM=xterm

RUN \
    echo "@edge http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk --no-cache update && \
    apk --no-cache upgrade && \
    apk --no-cache --update add \
      libgcc libstdc++ \
      mosquitto@edge protobuf@edge \
      # supervisor mosquitto@edge protobuf@edge \
      net-snmp@edge net-snmp-libs@edge net-snmp-tools@edge net-snmp-perl@edge \
    #   curl "libpq@edge<9.7" "postgresql-client@edge<9.7" "postgresql@edge<9.7" "postgresql-contrib@edge<9.7" && \
    # mkdir /docker-entrypoint-initdb.d /var/log/supervisord /var/log/rna_umbrella && \
    # curl -o /usr/local/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/1.2/gosu-amd64" && \
    # chmod +x /usr/local/bin/gosu && \
    # apk del curl && \
    rm -rf /var/cache/apk/*

ENV MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh
# ENV PGDATA /var/lib/postgresql/data MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh
# VOLUME /var/lib/postgresql/data

# COPY config/supervisor/supervisord.conf /etc/supervisor/conf.d/ 
# COPY rel/rancher_boot.sh /opt/app/bin/
# COPY config/postgres/postgres_init /usr/sbin/
# RUN chmod +x /usr/sbin/postgres_init && chmod +x /opt/app/bin/rancher_boot.sh

WORKDIR /opt/app
ADD rna_umbrella.tar.gz ./
