# ./docker-compose.yml
icx_manager:
  build: .
  dockerfile: ./docker/Dockerfile.build.elixir # That's our Dockerfile path
  env_file: .env # Set environment variables from an `.env` file, if needed
  command: /app/releases/rna_umbrella/bin/rna_umbrella foreground # Start the server if no other command is specified
  environment:
    - MIX_ENV=prod # That's the environment mode, you know
    - PORT=9006
    - PG_HOST=postgres
    - PG_USERNAME=postgres
  volumes:
    - .:/app # Here we're mounting our project's root directory inside the container
  ports:
    - "8006:9006"
  links:
    - postgres

postgres:
  image: postgres:9.6.2 # https://hub.docker.com/_/postgres/
  ports:
    - "5432"
