FROM elixir:1.4.2

MAINTAINER Yeong Sheng Tan <tanyeongsheng@gmail.com>

ENV REFRESHED_AT 2017-03-20
ENV DEBIAN_FRONTEND=noninteractive

# Install hex
RUN apt-get update && apt-get install -y snmp
RUN /usr/local/bin/mix local.hex --force && \
/usr/local/bin/mix local.rebar --force && \
/usr/local/bin/mix hex.info && \
/usr/local/bin/mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

WORKDIR /app
COPY . .

RUN MIX_ENV=prod /usr/local/bin/mix do deps.update --all
# RUN MIX_ENV=prod /usr/local/bin/mix do deps.update --all, compile.all
# RUN /usr/local/bin/mix ecto.create && mix ecto.migrate
RUN MIX_ENV=prod mix release --env=prod
# RUN ls -alrth /app/releases && ls -alrth /app/releases/rna_umbrella && ls -alrth /app/releases/rna_umbrella/bin

# CMD ["bash"]
