FROM elixir:1.4.2-slim

MAINTAINER Yeong Sheng Tan <tanyeongsheng@gmail.com>

ENV REFRESHED_AT 2017-03-22
ENV DEBIAN_FRONTEND=noninteractive

# Install hex
RUN apt-get update -q && apt-get upgrade -y && \
  apt-get install -y --no-install-recommends mosquitto mosquitto-clients protobuf-compiler snmp && \
#  htop rsyslog netcat net-tools vim-nox && \
  apt-get purge -y --auto-remove && \
  rm -rf /var/lib/apt/lists/*
RUN mix local.hex --force && \
  mix local.rebar --force && \
  mix hex.info && \
  mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

# Setup rsyslog client config and restart rsyslog
# COPY ./config/syslog/rsyslog.conf /etc/
# Enable systemctl to startup rsyslog on container bootup
# this assumes a full fledged init system; need to re-engineer for single purpose containers)
# RUN /bin/systemctl enable rsyslog

# Copy app releases to target container
ENV MIX_ENV=prod
WORKDIR /app
COPY . .

RUN mix do deps.update --all, phx.digest, release --env=prod --upgrade