FROM elixir:1.6.1-slim

MAINTAINER Yeong Sheng Tan <tanyeongsheng@gmail.com>

ENV REFRESHED_AT 2018-01-31 \
    DEBIAN_FRONTEND=noninteractive \
    SHELL=/bin/sh \
    LANG=en_US.UTF-8 \
    LC_ALL=${LANG} \
    HOME=/opt/app/ \
    TERM=xterm

# Install hex
RUN apt-get update -q && apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
    ca-certificates git protobuf-compiler snmp \
    git mosquitto protobuf-compiler snmp && \
  # htop rsyslog netcat net-tools vim-nox && \
  apt-get purge -y --auto-remove && \
  update-ca-certificates && \
  rm -rf /var/lib/apt/lists/*

# Install/update mix/hex/rebar and phoenix 1.3
RUN \
  mix local.hex --force && \
  mix local.rebar --force && \
  mix hex.info

ENV MIX_ENV=prod REPLACE_OS_VARS=true
WORKDIR /opt/app

# Cache elixir deps
COPY mix.exs mix.lock ./
RUN mkdir -p apps/rna/config
COPY apps/rna/mix.exs apps/rna/
COPY apps/rna/config/* apps/rna/config/
RUN mkdir -p apps/rna_web/config
COPY apps/rna_web/mix.exs apps/rna_web/
COPY apps/rna_web/config/* apps/rna_web/config/
RUN mix do deps.get, deps.compile

COPY . .

RUN mix do phx.digest, release --profile=rna_umbrella:prod --verbose && \
    tar xzf ./_build/prod/rel/rna_umbrella/releases/0.3.0/rna_umbrella.tar.gz && \
    rm -rf ./_build ./apps ./mix.*
